### ISSUE TITLE
Asset are removed which should not be removed

### ISSUE THREAD

**Issue by jimrojerTNO** [Multi-Energy-Systems-Optimization/mesido#13]
https://github.com/Project-OMOTES/user_feedback/issues/36

**Comment by KobusVanRooyen** [comment]
- Reason/cause: The solver failed
- Several asset inputs are missing in the network, like heating demand profile and buffer tank values.
- These assets were updated, then the solver (MESIDO) was successful but the case still failed in the PoC environment.
- No further action is required at the moment since MESIDO will be used in NWN in the near future
