### ISSUE TITLE
Bug in writing optimised pipe sizes to ESDL when supply and return pipes not linked with "_ret" in name

### ISSUE THREAD

**Issue by FJanssen-TNO** [Multi-Energy-Systems-Optimization/mesido#73]
write_output.py
When supply and return pipe are not linked with "_ret" in name the loop over the pipes cannot find cold_pipe as only loop over hot_pipes is used.

See ESDL below, run with EndScenarioSizingStagedHighs in PoCTutorial folder.
This ESDL is not working, however if the name of "Pipe1_ret" gets changed to "Pipe1_123_ret" it should work.

I haven't touched the ids so the ids and names don't have to be the same.

![error_pipe_name](https://github.com/Multi-Energy-Systems-Optimization/mesido/assets/137757789/401a62b7-a6de-4af0-9a79-77148c069e59)

[PoC Tutorial_pipes.esdl.txt](https://github.com/Multi-Energy-Systems-Optimization/mesido/files/15455717/PoC.Tutorial_pipes.esdl.txt)

**Comment by KobusVanRooyen** [comment]
@FJanssen-TNO:
- Yes the write_output.py does not cater for the scenario where supply and return pipe are not named like: "Pipe1" & "Pipe1_ret".
- It should be note that MESIDO also does not cater for this scenario. The code does run and will give a result when the supply and return pipe does not follow this naming convention. But the results will be different due to "Pipe1" not having a neighbour and therefore the heat losses will be different.
- It rest of MESIDO also has to be checked to see where the neighbour is important, because the rest of the code will also have to cater for a neighbpour pipe which does not follow this naming convention for the return pipe->"..._ret"

**Comment by KobusVanRooyen** [comment]
- the write_updated_esdl now caters for when the "_ret" is not used in the return pipe
- PoC tutorial updated such that the return pipe name is "Pipe1_cold_pipe" instead of "Pipe1_ret"
Still to check:
- [ ] the return pipe size is now DN250 instead of DN150. Not sure why this is happening @FJanssen-TNO  ?
